package snowballclass.payment.application.exception.payment

import snowballclass.payment.application.exception.CustomApplicationException
import snowballclass.payment.application.exception.ApplicationErrorCode

class TossPaymentInternalServerException(
	applicationErrorCode: ApplicationErrorCode
): CustomApplicationException(applicationErrorCode) {}