# 서버 포트
server:
  port: 8083

# 스프링 설정
spring:
  # 서버명
  application:
    name: payment
  # jpa 설정
  jpa:
    hibernate:
      # db 핸들링 by jpa
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    open-in-view: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://43.203.119.187:3306/payment?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: snowball
    password: 1234

# toss 설정
toss:
  client-key: "test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6"

# swagger 관련 설정
springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  paths-to-match: /**
  swagger-ui:
    path: /
    display-request-duration: true
    groups-order: desc
    operations-sorter: alpha
    disable-swagger-default-url: true
  api-docs:
    groups:
      enabled: true
tag:
  version: 1.0.0

# MSA 서버 설정
service:
  member:
    url: "http://snowball-class.shop:30001"
  lesson:
    url: "http://snowball-class.shop:30002"
  cart:
    url: "http://snowball-class.shop:30004"
  view:
    url: "http://localhost:8087"